name: Daily YouTube Watch & Upload

# Run at 03:30 UTC => 09:00 IST
on:
  schedule:
    - cron: "30 3 * * *"
  workflow_dispatch: # Allows manual runs

jobs:
  run-and-upload:
    runs-on: ubuntu-latest
    timeout-minutes: 360  # 6 hours max
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install rclone
        run: |
          sudo apt-get update -y
          sudo apt-get install -y rclone
          rclone --version

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install yt-dlp

      # --- THIS STEP IS NEW ---
      - name: Configure rclone
        env:
          RCLONE_CONF: ${{ secrets.RCLONE_CONF_CONTENT }}
        run: |
          mkdir -p ~/.config/rclone
          echo "$RCLONE_CONF" > ~/.config/rclone/rclone.conf
          rclone listremotes # Should output "gdrive:"

      - name: Run Watcher & Uploader Script
        env:
          # --- Pass secrets to Python script ---
          CHANNEL_URL: ${{ secrets.CHANNEL_URL }}
          GDRIVE_UPLOAD_FOLDER: ${{ secrets.GDRIVE_UPLOAD_FOLDER }} # Still uses the folder name
          
          # --- Pass cookie secrets ---
          YT_COOKIES: ${{ secrets.YT_COOKIES }}
          COOKIE_FILE_PATH: /tmp/yt-cookies.txt

          # --- Script settings ---
          OUT_DIR: ./downloads
          MAX_RUN_SECONDS: 18000   # 5 hours; adjust as needed
        run: |
          mkdir -p downloads
          
          # Create the cookie file securely from the secret
          if [ -n "$YT_COOKIES" ]; then
            echo "$YT_COOKIES" > $COOKIE_FILE_PATH
            echo "Cookie file created at $COOKIE_FILE_PATH"
          else
            echo "WARNING: YT_COOKIES secret is not set. Proceeding unauthenticated."
          fi
          
          # Run the script
          python yt_live_watcher.py